<!DOCTYPE html>
<html lang="en">
<head>

	<title>Document</title>

	<style>

		body{
			background-color: #212121;
			color: #c5c1c1;
			
		}

	</style>
</head>



<body>
	
	<h1>Hello Everyone !! </h1>


</body>




<script>

let h1 = document.querySelector('h1')

function changeColor(color, delay) {
	return new Promise ((resolve, reject) => {
			setTimeout(() => {
				let num = Math.floor((Math.random()*5)+1)
				if(num > 3 ){
					reject(`promise rejected`);     // ‚ùå‚ùå Bcoz of this on the basis of 'RANDOM-NUMBER' any of our promise could get rejected
				}

				h1.style.color = color
				resolve ('color changed')  
				console.log(`'${color}' color Got Executed`);  
			}, delay)
		})
}


// async function colorDemo () {
// 		await changeColor('red',     1000)
// 		await changeColor('green',   1000)
// 		await changeColor('blue',    1000)
// 		await changeColor('pink',    1000)
// 		await changeColor('yellow',  1000)

// 		let a = 5;                              // ‚ùå‚ùå & Bcoz of these REJECTIONS these works will never get executed
// 		console.log(a);							// -----------------(1)
// 		console.log('new number = ', a + 3);
// 	}


				// üîΩüîΩ [& to avoid the problems like at (1), 
				//        we execute the code like following üëáüëá]


async function colorDemo1 () {
	try{                     				//üçÅ‚úÖ The code which is having the possibility of getting an "error" enclose it inside TRY
		await changeColor('red',     1000)
		await changeColor('green',   1000)
		await changeColor('blue',    1000)
		await changeColor('seagreen',1000)
		await changeColor('yellow',  1000)
		await changeColor('pink',    1000)
		await changeColor('orange',  1000)
	} catch (errr0rrr) {       			    //üçÅ‚úÖ catch() will catch the error
		console.log(`ERROR CAUGHT & it was '${errr0rrr}' `);
	}
		
		let a = 5;                             
		console.log(a);							
		console.log('new number = ', a + 3);
	}

	// colorDemo1 ()


	/*‚úÖ‚úÖ NOTE:- So whenever we gonna call/use PROMISE or wait a PROMISE &&
	               whenever we use AWAIT, so we try to put them all the
				   AWAIT statements in TRY block & if by chance the the PROMISE
				   gets rejected, so to handle those rejections we gonna use 
				   CATCH (so that the tasks which lies beyond that don't get stopped
				   from getting executed)
	*/








</script>


</html>